DROP TABLE IF EXISTS whiteboard_shapes CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS project_invites CASCADE;
DROP TABLE IF EXISTS project_members CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS users CASCADE;
